// react-app/src/pages/designer/DesignerClients.jsx
// src/pages/designer/DesignerClients.jsx
import { useState, useEffect, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { selectUserInfo } from '@/store/slices/authSlice';

// Mock API
const mockAPI = {
  getClients: async () => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve([
          { id: 101, firstName: 'Jane', lastName: 'Cooper', email: 'jane@example.com', phone: '+233 24 123 4567', location: 'Accra, Ghana' },
          { id: 102, firstName: 'Alex', lastName: 'Morgan', email: 'alex@example.com', phone: '+233 20 987 6543', location: 'Kumasi, Ghana' },
          { id: 103, firstName: 'Sarah', lastName: 'Johnson', email: 'sarah@example.com', phone: '+233 27 555 1234', location: 'Takoradi, Ghana' },
          { id: 104, firstName: 'Michael', lastName: 'Brown', email: 'michael@example.com', phone: '+233 24 777 8888', location: 'Accra, Ghana' },
          { id: 105, firstName: 'Emily', lastName: 'Davis', email: 'emily@example.com', phone: '+233 20 111 2222', location: 'Cape Coast, Ghana' },
        ]);
      }, 300);
    });
  },

  getOrders: async (designerId) => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve([
          { id: 1, clientId: 101, designerId, orderDate: '2025-01-15', status: 'Completed', totalPrice: 450 },
          { id: 2, clientId: 102, designerId, orderDate: '2025-01-20', status: 'In Progress', totalPrice: 320 },
          { id: 3, clientId: 101, designerId, orderDate: '2025-02-01', status: 'Completed', totalPrice: 280 },
          { id: 4, clientId: 103, designerId, orderDate: '2025-02-05', status: 'Pending', totalPrice: 550 },
          { id: 5, clientId: 104, designerId, orderDate: '2025-02-10', status: 'In Progress', totalPrice: 420 },
          { id: 6, clientId: 101, designerId, orderDate: '2025-02-15', status: 'In Progress', totalPrice: 380 },
          { id: 7, clientId: 105, designerId, orderDate: '2025-02-20', status: 'Pending', totalPrice: 290 },
        ]);
      }, 200);
    });
  },
};

// Helper functions
const formatCurrency = (value) => `₵${Number(value || 0).toFixed(2)}`;

const getBadgeClass = (status) => {
  const classes = {
    Active: 'bg-green-100 text-green-800',
    Inactive: 'bg-red-100 text-red-800',
    New: 'bg-yellow-100 text-yellow-800',
  };
  return `${classes[status] || 'bg-gray-100 text-gray-800'} px-2 py-1 rounded-full text-xs font-medium`;
};

// Stat Card Component
const StatCard = ({ title, value, icon, bgColor, iconColor, growth }) => (
  <div className="bg-white p-4 sm:p-6 rounded-lg shadow-sm">
    <div className="flex justify-between items-center">
      <div>
        <p className="text-gray-500 text-xs sm:text-sm">{title}</p>
        <p className="text-2xl sm:text-3xl font-bold text-gray-800">{value}</p>
      </div>
      <div className={`p-3 rounded-full ${bgColor}`}>
        <svg className={`h-5 w-5 sm:h-6 sm:w-6 ${iconColor}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={icon} />
        </svg>
      </div>
    </div>
    <div className="mt-2">
      <span className="text-green-500 text-xs sm:text-sm flex items-center">
        <svg className="h-3 w-3 sm:h-4 sm:w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 10l7-7m0 0l7 7m-7-7v18" />
        </svg>
        {growth}
      </span>
    </div>
  </div>
);

// Main Component
const DesignerClients = () => {
  const navigate = useNavigate();
  const userInfo = useSelector(selectUserInfo);

  // State
  const [isLoading, setIsLoading] = useState(true);
  const [clients, setClients] = useState([]);
  const [orders, setOrders] = useState([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [selectAll, setSelectAll] = useState(false);
  const [selectedClients, setSelectedClients] = useState({});

  const itemsPerPage = 5;

  // Fetch data
  useEffect(() => {
    const fetchData = async () => {
      try {
        const [clientsData, ordersData] = await Promise.all([
          mockAPI.getClients(),
          mockAPI.getOrders(userInfo?.id),
        ]);
        setClients(clientsData);
        setOrders(ordersData);
      } catch (error) {
        console.error('Error fetching data:', error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchData();
  }, [userInfo?.id]);

  // Reset page when filters change
  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, statusFilter]);

  // Process clients with order data
  const designerClients = useMemo(() => {
    const designerOrders = orders.filter((o) => o.designerId === userInfo?.id);
    const clientIds = [...new Set(designerOrders.map((o) => o.clientId))];

    return clientIds.map((clientId) => {
      const client = clients.find((c) => c.id === clientId);
      if (!client) return null;

      const clientOrders = designerOrders.filter((o) => o.clientId === clientId);
      const latestOrder = clientOrders.reduce((latest, order) =>
        !latest || new Date(order.orderDate) > new Date(latest.orderDate) ? order : latest, null
      );
      const totalSpent = clientOrders.reduce((sum, o) => sum + (o.totalPrice || 0), 0);
      const isActive = clientOrders.some((o) => o.status === 'In Progress');

      return {
        id: client.id,
        name: `${client.firstName} ${client.lastName}`,
        email: client.email,
        location: client.location || 'N/A',
        phone: client.phone || 'N/A',
        lastOrder: latestOrder?.orderDate || 'N/A',
        totalOrders: clientOrders.length,
        totalSpent: formatCurrency(totalSpent),
        status: isActive ? 'Active' : 'Inactive',
      };
    }).filter(Boolean);
  }, [clients, orders, userInfo?.id]);

  // Client stats
  const clientStats = useMemo(() => {
    const designerOrders = orders.filter((o) => o.designerId === userInfo?.id);
    const uniqueClientIds = [...new Set(designerOrders.map((o) => o.clientId))];

    const clientOrderCounts = designerOrders.reduce((acc, o) => {
      acc[o.clientId] = (acc[o.clientId] || 0) + 1;
      return acc;
    }, {});

    const repeatClientIds = Object.keys(clientOrderCounts).filter((id) => clientOrderCounts[id] > 1);
    const activeClientIds = [...new Set(designerOrders.filter((o) => o.status === 'In Progress').map((o) => o.clientId))];

    const lastMonth = new Date();
    lastMonth.setMonth(lastMonth.getMonth() - 1);
    const newClientIds = [...new Set(
      designerOrders.filter((o) => new Date(o.orderDate) >= lastMonth).map((o) => o.clientId)
    )];

    return [
      {
        title: 'Total Clients',
        value: uniqueClientIds.length,
        icon: 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z',
        bgColor: 'bg-purple-100',
        iconColor: 'text-purple-900',
        growth: uniqueClientIds.length > 0 ? `${Math.round((newClientIds.length / uniqueClientIds.length) * 100)}% this month` : '0%',
      },
      {
        title: 'Active Clients',
        value: activeClientIds.length,
        icon: 'M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z',
        bgColor: 'bg-green-100',
        iconColor: 'text-green-600',
        growth: uniqueClientIds.length > 0 ? `${Math.round((activeClientIds.length / uniqueClientIds.length) * 100)}% of total` : '0%',
      },
      {
        title: 'New Clients',
        value: newClientIds.length,
        icon: 'M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z',
        bgColor: 'bg-blue-100',
        iconColor: 'text-blue-600',
        growth: `${newClientIds.length} this month`,
      },
      {
        title: 'Repeat Clients',
        value: repeatClientIds.length,
        icon: 'M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15',
        bgColor: 'bg-purple-100',
        iconColor: 'text-purple-900',
        growth: uniqueClientIds.length > 0 ? `${Math.round((repeatClientIds.length / uniqueClientIds.length) * 100)}% of total` : '0%',
      },
    ];
  }, [orders, userInfo?.id]);

  // Filtered and paginated clients
  const filteredClients = useMemo(() => {
    let result = designerClients;

    if (searchQuery) {
      const query = searchQuery.toLowerCase();
      result = result.filter((c) =>
        c.name.toLowerCase().includes(query) ||
        c.email.toLowerCase().includes(query) ||
        c.location.toLowerCase().includes(query) ||
        c.phone.toLowerCase().includes(query)
      );
    }

    if (statusFilter) {
      result = result.filter((c) => c.status === statusFilter);
    }

    return result;
  }, [designerClients, searchQuery, statusFilter]);

  const totalPages = Math.ceil(filteredClients.length / itemsPerPage);
  const paginatedClients = filteredClients.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  // Handlers
  const viewClient = (id) => navigate(`/designer/clients/${id}`);
  const messageClient = (id) => console.log(`Message client: ${id}`);
  const callClient = (client) => client.phone && (window.location.href = `tel:${client.phone}`);
  const emailClient = (client) => client.email && (window.location.href = `mailto:${client.email}`);

  const toggleSelectAll = () => {
    const newSelectAll = !selectAll;
    setSelectAll(newSelectAll);
    const newSelected = {};
    if (newSelectAll) {
      paginatedClients.forEach((c) => { newSelected[c.id] = true; });
    }
    setSelectedClients(newSelected);
  };

  const toggleSelectClient = (id) => {
    setSelectedClients((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  if (isLoading) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-purple-900" />
      </div>
    );
  }

  return (
    <div className="bg-gray-50 min-h-screen">
      {/* Header */}
      <div className="p-4 sm:p-6 bg-white shadow-sm">
        <h1 className="text-xl sm:text-2xl font-bold text-gray-800">Clients</h1>
        <p className="text-gray-600 text-sm sm:text-base">Manage your client relationships and track client information</p>
      </div>

      {/* Stats */}
      <div className="p-4 sm:p-6">
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {clientStats.map((stat) => (
            <StatCard key={stat.title} {...stat} />
          ))}
        </div>
      </div>

      {/* Search & Filter */}
      <div className="px-4 sm:px-6 pb-4">
        <div className="bg-white p-4 rounded-lg shadow-sm">
          <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4">
            <h2 className="text-lg font-semibold">Client List</h2>
            <div className="flex flex-col sm:flex-row w-full lg:w-auto gap-3">
              <div className="relative flex-1 sm:w-64">
                <svg className="h-5 w-5 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
                <input
                  type="text"
                  placeholder="Search clients..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                />
              </div>
              <div className="flex gap-2">
                <select
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value)}
                  className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                >
                  <option value="">All Clients</option>
                  <option value="Active">Active</option>
                  <option value="Inactive">Inactive</option>
                </select>
                <button className="px-4 py-2 bg-purple-900 hover:bg-purple-800 text-white rounded-lg font-medium flex items-center gap-2">
                  <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                  </svg>
                  <span className="hidden sm:inline">Add Client</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Table */}
      <div className="px-4 sm:px-6 pb-6">
        <div className="bg-white rounded-lg shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-4 py-3 text-left">
                    <input
                      type="checkbox"
                      checked={selectAll}
                      onChange={toggleSelectAll}
                      className="rounded border-gray-300"
                    />
                  </th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Client</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase hidden md:table-cell">Email</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase hidden lg:table-cell">Last Order</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase hidden sm:table-cell">Orders</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase hidden lg:table-cell">Spent</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {paginatedClients.length === 0 ? (
                  <tr>
                    <td colSpan="8" className="px-4 py-12 text-center">
                      <svg className="h-12 w-12 text-gray-400 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
                      </svg>
                      <p className="text-gray-500">No clients found</p>
                      <p className="text-gray-400 text-sm mt-1">Try adjusting your search or filter criteria</p>
                    </td>
                  </tr>
                ) : (
                  paginatedClients.map((client) => (
                    <tr key={client.id} className="hover:bg-gray-50">
                      <td className="px-4 py-4">
                        <input
                          type="checkbox"
                          checked={selectedClients[client.id] || false}
                          onChange={() => toggleSelectClient(client.id)}
                          className="rounded border-gray-300"
                        />
                      </td>
                      <td className="px-4 py-4">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-full bg-purple-100 flex items-center justify-center flex-shrink-0">
                            <span className="text-purple-900 font-bold text-sm">{client.name.charAt(0)}</span>
                          </div>
                          <div className="min-w-0">
                            <div className="font-medium truncate">{client.name}</div>
                            <div className="text-sm text-gray-500 truncate">{client.location}</div>
                          </div>
                        </div>
                      </td>
                      <td className="px-4 py-4 hidden md:table-cell text-sm">{client.email}</td>
                      <td className="px-4 py-4 hidden lg:table-cell text-sm">{client.lastOrder}</td>
                      <td className="px-4 py-4 hidden sm:table-cell text-sm">{client.totalOrders}</td>
                      <td className="px-4 py-4 hidden lg:table-cell text-sm font-medium">{client.totalSpent}</td>
                      <td className="px-4 py-4">
                        <span className={getBadgeClass(client.status)}>{client.status}</span>
                      </td>
                      <td className="px-4 py-4">
                        <div className="flex gap-1">
                          <button onClick={() => viewClient(client.id)} className="p-2 hover:bg-gray-100 rounded" title="View">
                            <svg className="h-4 w-4 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                            </svg>
                          </button>
                          <button onClick={() => emailClient(client)} className="p-2 hover:bg-gray-100 rounded" title="Email">
                            <svg className="h-4 w-4 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                            </svg>
                          </button>
                          <button onClick={() => callClient(client)} className="p-2 hover:bg-gray-100 rounded" title="Call">
                            <svg className="h-4 w-4 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                            </svg>
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          <div className="flex flex-col sm:flex-row justify-between items-center p-4 border-t gap-4">
            <div className="text-sm text-gray-500">
              {filteredClients.length > 0 ? (
                <>Showing {(currentPage - 1) * itemsPerPage + 1}-{Math.min(currentPage * itemsPerPage, filteredClients.length)} of {filteredClients.length} clients</>
              ) : (
                'No clients found'
              )}
            </div>
            {totalPages > 1 && (
              <div className="flex gap-1">
                <button
                  onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
                  disabled={currentPage === 1}
                  className="px-3 py-1 border rounded hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  «
                </button>
                {[...Array(totalPages)].map((_, i) => (
                  <button
                    key={i}
                    onClick={() => setCurrentPage(i + 1)}
                    className={`px-3 py-1 border rounded ${currentPage === i + 1 ? 'bg-purple-900 text-white' : 'hover:bg-gray-50'}`}
                  >
                    {i + 1}
                  </button>
                ))}
                <button
                  onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
                  disabled={currentPage === totalPages}
                  className="px-3 py-1 border rounded hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  »
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default DesignerClients;

// src/components/designer/DesignerClients.vue
<script setup>
import { ref, computed, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useClientStore } from '@/stores/clientStore';
import { useOrdersStore } from '@/stores/ordersStore';
import { useUserStore } from '@/stores/auth';

const router = useRouter();
const clientStore = useClientStore();
const ordersStore = useOrdersStore();
const userStore = useUserStore();

// Initialize data
onMounted(async () => {
  if (clientStore.clients.length === 0) {
    await clientStore.fetchClients();
  }
  
  if (ordersStore.orders.length === 0) {
    await ordersStore.fetchOrders();
  }
  
  // Reset filters and pagination
  currentPage.value = 1;
  searchQuery.value = '';
  statusFilter.value = '';
});

// Router
function viewClient(id) {
  router.push(`/designer/clients/${id}`);
}

// Computed data for client stats
const clientStats = computed(() => {
  // Get current designer ID
  const designerId = userStore.userInfo?.id;
  if (!designerId) return defaultStats.value;
  
  const designerOrders = ordersStore.getOrdersByDesignerId(designerId);
  
  // Get unique client IDs from orders
  const uniqueClientIds = [...new Set(designerOrders.map(order => order.clientId))];
  
  // Get clients who ordered more than once
  const clientOrderCounts = designerOrders.reduce((acc, order) => {
    acc[order.clientId] = (acc[order.clientId] || 0) + 1;
    return acc;
  }, {});
  
  const repeatClientIds = Object.keys(clientOrderCounts).filter(
    clientId => clientOrderCounts[clientId] > 1
  );
  
  // Get active clients (with in-progress orders)
  const activeOrders = designerOrders.filter(order => order.status === 'In Progress');
  const activeClientIds = [...new Set(activeOrders.map(order => order.clientId))];
  
  // Get new clients (ordered in the last month)
  const lastMonth = new Date();
  lastMonth.setMonth(lastMonth.getMonth() - 1);
  
  const newOrders = designerOrders.filter(order => {
    const orderDate = new Date(order.orderDate);
    return orderDate >= lastMonth;
  });
  
  const newClientIds = [...new Set(newOrders.map(order => order.clientId))];
  
  return [
    {
      title: 'Total Clients',
      value: uniqueClientIds.length,
      iconBg: 'purple-100',
      iconColor: 'text-purple-900',
      iconPath: 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z',
      growth: uniqueClientIds.length > 0 ? `${Math.round((newClientIds.length / uniqueClientIds.length) * 100)}% this month` : '0% this month'
    },
    {
      title: 'Active Clients',
      value: activeClientIds.length,
      iconBg: 'green-100',
      iconColor: 'text-green-600',
      iconPath: 'M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z',
      growth: activeClientIds.length > 0 ? `${Math.round((activeClientIds.length / uniqueClientIds.length) * 100)}% of total` : '0% of total'
    },
    {
      title: 'New Clients',
      value: newClientIds.length,
      iconBg: 'blue-100',
      iconColor: 'text-blue-600',
      iconPath: 'M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z',
      growth: `${newClientIds.length} this month`
    },
    {
      title: 'Repeat Clients',
      value: repeatClientIds.length,
      iconBg: 'purple-100',
      iconColor: 'text-purple-900',
      iconPath: 'M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15',
      growth: repeatClientIds.length > 0 ? `${Math.round((repeatClientIds.length / uniqueClientIds.length) * 100)}% of total` : '0% of total'
    }
  ];
});

// Default stats for when we don't have data yet
const defaultStats = ref([
  {
    title: 'Total Clients',
    value: 0,
    iconBg: 'purple-100',
    iconColor: 'text-purple-900',
    iconPath: 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z',
    growth: '0% this month'
  },
  {
    title: 'Active Clients',
    value: 0,
    iconBg: 'green-100',
    iconColor: 'text-green-600',
    iconPath: 'M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z',
    growth: '0% of total'
  },
  {
    title: 'New Clients',
    value: 0,
    iconBg: 'blue-100',
    iconColor: 'text-blue-600',
    iconPath: 'M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z',
    growth: '0 this month'
  },
  {
    title: 'Repeat Clients',
    value: 0,
    iconBg: 'purple-100',
    iconColor: 'text-purple-900',
    iconPath: 'M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15',
    growth: '0% of total'
  }
]);

// Filtering and sorting
const searchQuery = ref('');
const statusFilter = ref('');
const selectAll = ref(false);
const currentPage = ref(1);
const itemsPerPage = 5;

// Get designer's clients from orders
const designerClients = computed(() => {
  const designerId = userStore.userInfo?.id;
  if (!designerId || !ordersStore.orders.length) return [];
  
  // Get all orders for this designer
  const designerOrders = ordersStore.getOrdersByDesignerId(designerId);
  
  // Get unique client IDs
  const clientIds = [...new Set(designerOrders.map(order => order.clientId))];
  
  // Get client details for each ID
  const clients = clientIds.map(clientId => {
    const client = clientStore.getClientById(clientId);
    if (!client) return null;
    
    // Get all orders for this client with this designer
    const clientOrders = designerOrders.filter(order => order.clientId === clientId);
    
    // Get latest order date
    const latestOrder = clientOrders.reduce((latest, order) => {
      return !latest || new Date(order.orderDate) > new Date(latest.orderDate) ? order : latest;
    }, null);
    
    // Calculate total spent
    const totalSpent = clientOrders.reduce((sum, order) => sum + (order.totalPrice || 0), 0);
    
    // Determine if client is active (has at least one active order)
    const isActive = clientOrders.some(order => order.status === 'In Progress');
    
    return {
      id: client.id,
      name: `${client.firstName} ${client.lastName}`,
      email: client.email,
      location: client.location || 'N/A',
      phone: client.phone || 'N/A',
      lastOrder: latestOrder ? latestOrder.orderDate : 'N/A',
      totalOrders: clientOrders.length,
      totalSpent: ordersStore.formatCurrency(totalSpent),
      status: isActive ? 'Active' : 'Inactive',
      selected: false
    };
  }).filter(Boolean); // Remove null entries
  
  return clients;
});

// Computed properties
const filteredClients = computed(() => {
  let result = designerClients.value;
  
  if (searchQuery.value) {
    const query = searchQuery.value.toLowerCase();
    result = result.filter(client => 
      client.name.toLowerCase().includes(query) || 
      client.email.toLowerCase().includes(query) ||
      client.location.toLowerCase().includes(query) ||
      (client.phone && client.phone.toLowerCase().includes(query))
    );
  }
  
  if (statusFilter.value) {
    result = result.filter(client => client.status === statusFilter.value);
  }
  
  // Pagination
  const startIndex = (currentPage.value - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  return result.slice(startIndex, endIndex);
});

const totalClients = computed(() => {
  let result = designerClients.value;
  
  if (searchQuery.value) {
    const query = searchQuery.value.toLowerCase();
    result = result.filter(client => 
      client.name.toLowerCase().includes(query) || 
      client.email.toLowerCase().includes(query) ||
      client.location.toLowerCase().includes(query) ||
      (client.phone && client.phone.toLowerCase().includes(query))
    );
  }
  
  if (statusFilter.value) {
    result = result.filter(client => client.status === statusFilter.value);
  }
  
  return result.length;
});

const totalPages = computed(() => {
  return Math.ceil(totalClients.value / itemsPerPage);
});

const paginationStart = computed(() => {
  return totalClients.value === 0 ? 0 : (currentPage.value - 1) * itemsPerPage + 1;
});

const paginationEnd = computed(() => {
  return Math.min(currentPage.value * itemsPerPage, totalClients.value);
});

// Methods
function getBadgeClass(status) {
  switch (status) {
    case 'Active': return 'badge-success';
    case 'Inactive': return 'badge-error';
    case 'New': return 'badge-warning';
    default: return 'badge-info';
  }
}

function toggleSelectAll() {
  designerClients.value.forEach(client => {
    if (
      !searchQuery.value ||
      client.name.toLowerCase().includes(searchQuery.value.toLowerCase()) ||
      client.email.toLowerCase().includes(searchQuery.value.toLowerCase())
    ) {
      client.selected = selectAll.value;
    }
  });
}

function prevPage() {
  if (currentPage.value > 1) {
    currentPage.value--;
  }
}

function nextPage() {
  if (currentPage.value < totalPages.value) {
    currentPage.value++;
  }
}

function goToPage(page) {
  currentPage.value = page;
}

function messageClient(id) {
  console.log(`Message client with ID: ${id}`);
  // Open messaging interface or redirect to messaging page
  // router.push(`/designer/messages?client=${id}`);
}

function callClient(id) {
  const client = designerClients.value.find(c => c.id === id);
  if (client && client.phone) {
    window.location.href = `tel:${client.phone}`;
  } else {
    console.log(`No phone number available for client with ID: ${id}`);
  }
}

function emailClient(id) {
  const client = designerClients.value.find(c => c.id === id);
  if (client && client.email) {
    window.location.href = `mailto:${client.email}`;
  } else {
    console.log(`No email available for client with ID: ${id}`);
  }
}
</script>

<template>
  <div class="bg-gray-50 min-h-screen">
    <!-- Client Page Header -->
    <div class="p-6 bg-white shadow-sm">
      <h1 class="text-2xl font-bold text-gray-800">Clients</h1>
      <p class="text-gray-600">Manage your client relationships and track client information</p>
    </div>

    <!-- Client Statistics -->
    <div class="p-6">
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div v-for="stat in clientStats" :key="stat.title" class="bg-white p-6 rounded-lg shadow-sm">
          <div class="flex justify-between items-center">
            <div>
              <p class="text-gray-500 text-sm">{{ stat.title }}</p>
              <p class="text-3xl font-bold text-gray-800">{{ stat.value }}</p>
            </div>
            <div :class="['p-3', 'rounded-full', stat.iconBg]">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" :class="stat.iconColor" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" :d="stat.iconPath" />
              </svg>
            </div>
          </div>
          <div class="mt-2">
            <span class="text-green-500 text-sm flex items-center">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 10l7-7m0 0l7 7m-7-7v18" />
              </svg>
              {{ stat.growth }}
            </span>
          </div>
        </div>
      </div>
    </div>

    <!-- Client Search and Filter -->
    <div class="p-6 pt-0">
      <div class="bg-white p-4 rounded-lg shadow-sm">
        <div class="flex flex-col md:flex-row justify-between items-center">
          <h2 class="text-lg font-semibold mb-4 md:mb-0">Client List</h2>
          <div class="flex flex-col md:flex-row w-full md:w-auto gap-4">
            <div class="relative w-full md:w-64">
              <input 
                type="text" 
                placeholder="Search clients..." 
                class="input input-bordered w-full pl-10" 
                v-model="searchQuery"
              />
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 absolute left-3 top-3 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </div>
            <div class="flex gap-2">
              <select class="select select-bordered w-full md:w-auto" v-model="statusFilter">
                <option value="">All Clients</option>
                <option value="Active">Active</option>
                <option value="Inactive">Inactive</option>
                <option value="New">New</option>
              </select>
              <button class="btn bg-purple-900 hover:bg-purple-800 text-white">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                </svg>
                Add Client
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Client Table -->
    <div class="p-6 pt-0">
      <div class="bg-white rounded-lg shadow-sm overflow-x-auto">
        <table class="table w-full">
          <thead>
            <tr>
              <th class="bg-gray-50">
                <label>
                  <input type="checkbox" class="checkbox checkbox-sm" v-model="selectAll" @change="toggleSelectAll" />
                </label>
              </th>
              <th class="bg-gray-50">Client</th>
              <th class="bg-gray-50">Email</th>
              <th class="bg-gray-50">Last Order</th>
              <th class="bg-gray-50">Total Orders</th>
              <th class="bg-gray-50">Total Spent</th>
              <th class="bg-gray-50">Status</th>
              <th class="bg-gray-50">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="filteredClients.length === 0">
              <td colspan="8" class="text-center py-8">
                <div class="flex flex-col items-center justify-center">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 text-gray-400 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
                  </svg>
                  <p class="text-gray-500">No clients found</p>
                  <p class="text-gray-400 text-sm mt-1">Try adjusting your search or filter criteria</p>
                </div>
              </td>
            </tr>
            <tr v-for="client in filteredClients" :key="client.id" class="hover:bg-gray-50">
              <td>
                <label>
                  <input type="checkbox" class="checkbox checkbox-sm" v-model="client.selected" />
                </label>
              </td>
              <td>
                <div class="flex items-center space-x-3">
                  <div class="avatar">
                    <div class="mask mask-squircle w-10 h-10 bg-purple-100 flex items-center justify-center">
                      <span class="text-purple-900 font-bold">{{ client.name.charAt(0) }}</span>
                    </div>
                  </div>
                  <div>
                    <div class="font-bold">{{ client.name }}</div>
                    <div class="text-sm opacity-50">{{ client.location }}</div>
                  </div>
                </div>
              </td>
              <td>{{ client.email }}</td>
              <td>{{ client.lastOrder }}</td>
              <td>{{ client.totalOrders }}</td>
              <td>{{ client.totalSpent }}</td>
              <td>
                <div :class="`badge ${getBadgeClass(client.status)} gap-2`">{{ client.status }}</div>
              </td>
              <td>
                <div class="flex gap-2">
                  <button class="btn btn-sm btn-ghost" @click="viewClient(client.id)">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                  </button>
                  <button class="btn btn-sm btn-ghost" @click="messageClient(client.id)">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                    </svg>
                  </button>
                  <button class="btn btn-sm btn-ghost" @click="callClient(client.id)">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                    </svg>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
        
        <!-- Pagination -->
        <div class="flex justify-between items-center p-4">
          <div class="text-sm text-gray-500">
            <span v-if="totalClients > 0">
              Showing {{ paginationStart }}-{{ paginationEnd }} of {{ totalClients }} clients
            </span>
            <span v-else>
              No clients found
            </span>
          </div>
          <div class="join" v-if="totalPages > 1">
            <button class="join-item btn btn-sm" @click="prevPage" :disabled="currentPage === 1">«</button>
            <button 
              v-for="page in totalPages" 
              :key="page" 
              class="join-item btn btn-sm" 
              :class="{ 'bg-purple-900 text-white': currentPage === page }"
              @click="goToPage(page)"
            >
              {{ page }}
            </button>
            <button class="join-item btn btn-sm" @click="nextPage" :disabled="currentPage === totalPages">»</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
